name: 16 - Working with Environments | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
        description: environment to deploy into

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    outputs:
      target-env: ${{ steps.echo.outputs.environment }}
    env:
      MY_ENV_VALUE: ${{ vars.environment || 'default value' }}
    steps:
      - name: Echo vars
        run: "Env variable: ${{ env.MY_ENV_VALUE }}"
