name: 17 - 1 - Custom Actions - Composite

run-name: "17 - 1 - Custom Actions - Composite | env: - ${{ inputs.target-env }}"

on:
  - workflow_dispatch

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: ${{ env.working-directory }}
      - name: Unit tests
        run: npm run test
      - name: Build code
        run: npm run build
