name: 17 - 1 - Custom Actions - Composite

run-name: "17 - 1 - Custom Actions - Composite | env: - ${{ inputs.target-env}}"

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                description: environment to deploy into
                options:
                    - dev
                    - prod

env:
    working-directory: 17-custom-actions/react-app

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - name: 1) Checkout code
              uses: actions/checkout@v4
            - name: 2) Setup Node and NPM dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                  node-version: 20.x
                  working-dir: ${{ env.working-directory }}
            - name: 3) Unit tests
              run: npm run test
            - name: 4) Build code
              run: npm run build
